E - Shopper (web đồ điện tử)/Models/Entities/Inward.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingOnline.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inward()
        {
            this.Inward_Detail = new HashSet<Inward_Detail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> TotalQuantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string RecivedInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inward_Detail> Inward_Detail { get; set; }
        public virtual User User { get; set; }
    }
}

E - Shopper (web đồ điện tử)/Models/Entities/Inward_Detail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingOnline.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward_Detail
    {
        public long ID { get; set; }
        public Nullable<long> Inward_ID { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Inward Inward { get; set; }
        public virtual Product Product { get; set; }
    }
}

E - Shopper (web đồ điện tử)/Areas/Seller/Controllers/InwardController.cs
using PagedList;
using ShoppingOnline.Models.Business;
using ShoppingOnline.Models.DTO;
using ShoppingOnline.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingOnline.Areas.Seller.Controllers
{
    public class InwardController : Controller
    {
        private Shopping_OnlineEntities db = new Shopping_OnlineEntities();
        // GET: Seller/Inward
        public ActionResult Index(int page = 1, int pagesize = 12)
        {
            var seller = Session["seller_login"] as User;
            if (seller == null)
                return Redirect("/User/Login");
            var model = db.Inwards.Where(x => x.User_ID == seller.ID).OrderByDescending(x => x.Createdate).ToPagedList(page, pagesize);
            //Thống kê tồn ko
            ViewBag.quantity_product = db.Products.Where(x => x.User_ID == seller.ID && x.Quantity > 0).OrderByDescending(x => x.Quantity).Take(12).ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            var seller = Session["seller_login"] as User;
            if (seller == null)
                return Redirect("/User/Login");
            ViewBag.lstproduct = db.Products.Where(x => x.User_ID == seller.ID).OrderByDescending(x => x.Product_Name).ToList();
            return View();
        }

        [HttpPost]
        public ActionResult AddInward(Inward entity)
        {
            var res = new InwardBusiness().addInward(entity);
            if (res)
            {
                var cart = (List<CartDTO>)Session["add_inward"];
                foreach (var item in cart)
                {
                    var detail = new Inward_Detail();
                    detail.Inward_ID = db.Inwards.Max(x => x.ID);
                    detail.Product_ID = item.Product.ID;
                    detail.Quantity = item.Quantity;

                    if (item.Product.Price != null)
                    {
                        detail.Price = item.Product.Price;
                        detail.Amount = (int)item.Product.Price * item.Quantity;
                    }
                    else
                    {
                        detail.Price = item.Product.Promotion_Price;
                        detail.Amount = (int)item.Product.Promotion_Price * item.Quantity;
                    }
                    new InwardBusiness().addInward_Detail(detail);

                    //Cộng tồn kho
                    new ProductBusiness().AddQuantity(item.Product.ID, item.Quantity);
                }
                Session["add_order"] = null;
                TempData["add_success"] = "Nhập kho thành công.";
                TempData["alert"] = "alert-success";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["alert"] = "alert-danger";
                TempData["add_success"] = "Nhập kho KHÔNG thành công.";
                return RedirectToAction("Add");
            }
        }


        public JsonResult addInwardProduct(long product_id, int quantity)
        {
            var product = db.Products.Find(product_id);
            var cart = Session["add_inward"];
            if (cart != null)//Nếu giỏ đã chứa sản phẩm
            {
                var list = (List<CartDTO>)cart;
                if (list.Exists(x => x.Product.ID == product.ID))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.ID == product.ID)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //Tạo đối tượng mới
                    var item = new CartDTO();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
            }
            else//nếu giỏ hàng trống
            {
                var item = new CartDTO();
                item.Product = product;
                item.Quantity = quantity;
                var list = new List<CartDTO>();
                list.Add(item);

                Session["add_inward"] = list;
            }
            return Json(new
            {
                status = true
            }, JsonRequestBehavior.AllowGet);

        }


        //Xóa từng sản phẩm
        public JsonResult Delete_InwardProduct(long ID)
        {
            var cartSec = (List<CartDTO>)Session["add_inward"];
            cartSec.RemoveAll(x => x.Product.ID == ID);
            Session["add_inward"] = cartSec;
            return Json(new
            {
                status = true
            });
        }

        //Sửa số lượng sp trong giỏ hàng
        public JsonResult Edit(long ID, int Quantity)
        {
            var productSec = (List<CartDTO>)Session["add_inward"];

            foreach (var item in productSec)
            {
                if (item.Product.ID == ID)
                {
                    item.Quantity = Quantity;
                }

            }

            Session["add_inward"] = productSec;
            return Json(new
            {
                status = true
            });
        }


        //Chi tiết nhập kho
        public ActionResult Inward_Detail(long ID)
        {
            var model = db.Inward_Detail.Where(x => x.Inward_ID == ID);
            ViewBag.Inward = db.Inwards.Find(ID);
            return View(model.ToList());
        }
    }
}

E - Shopper (web đồ điện tử)/Areas/Seller/Views/Inward/Add.cshtml
@using ShoppingOnline.Models.DTO;
@using ShoppingOnline.Models.Entities;

@{
    ViewBag.Title = "Nhập kho";
    Layout = "~/Areas/Seller/Views/Shared/_Layout.cshtml";
    float tong = 0;
    int total_quantity = 0;
    var add_inward = Session["add_inward"] as List<CartDTO>;
    var lstproduct = ViewBag.lstproduct as List<Product>;
    var seller = Session["seller_login"] as User;
}


<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-4">
                    <h3 class="page-header">Nhập kho</h3>
                </div>
                <div class="col-md-8" style="margin-top: 40px;">
                    <ol class="breadcrumb" style="text-align: right">
                        <li><a href="/Seller/Inward/Index"><i class="fa fa-inbox fa-fw"></i> Quản lý kho</a></li>
                        <li class="active">Nhập kho</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Nhập sản phẩm vào kho
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form action="" method="get">
                                    <div class="form-group col-md-4">
                                        <label>Tên sản phẩm</label>
                                        <select class="form-control select2" name="Product_Name" id="Product_ID">
                                            <option value="">---Chọn sản phẩm---</option>
                                            @foreach (var item in lstproduct)
                                            {
                                                <option value="@item.ID" >@item.Product_Name</option>
                                            }
                                        </select>

                                        @*<input type="text" class="form-control" name="Product_Name" id="Product_Name" placeholder="Nhập tên sản phẩm">*@
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label>Số lượng</label>
                                        <input type="number" class="form-control" name="Quantity" id="Quantity" placeholder="Nhập số lượng" min="1" value="1">
                                    </div>

                                    <div class="col-md-3" style="margin-top: 24px;">
                                        <button type="button" class="btn btn-default" id="btnAdd_InwardProduct">Thêm</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info">
                    <thead>
                        <tr role="row">
                            <th class="text-center" style="width: 20px;">
                                STT
                            </th>
                            <th class="text-center" style="width: 209px;">
                                Tên sản phẩm
                            </th>
                            <th class="text-center" style="width: 192px;">
                                Số lượng
                            </th>
                            <th class="text-center" style="width: 142px;">
                                Đơn giá
                            </th>
                            <th class="text-center" style="width: 142px;">
                                Thành tiền
                            </th>
                            <th class="text-center" style="width: 103px;">

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (add_inward != null)
                        {
                            int dem = 0;
                            float price = 0, price_promotion = 0;

                            foreach (var item in add_inward)
                            {
                                dem++;
                                if (item.Product.Price != null)
                                {
                                    price = (float)(item.Product.Price * item.Quantity);
                                    tong = tong + (float)price;
                                    total_quantity += item.Quantity;
                                    price_promotion = (float)item.Product.Price;
                                }
                                else
                                {
                                    price = (float)(item.Product.Promotion_Price * item.Quantity);
                                    tong = tong + (float)price;
                                    total_quantity += item.Quantity;
                                    price_promotion = (float)item.Product.Promotion_Price;
                                }

                                <tr class="gradeA even" role="row">
                                    <td class="sorting_1">@dem</td>
                                    <td>@item.Product.Product_Name</td>
                                    <td><input type="number" name="Quantity" value="@item.Quantity" min="1" class="form-control text-center" id="txtQuantity-@item.Product.ID" /></td>
                                    <td class="text-center">@price_promotion.ToString("N0")</td>
                                    <td class="text-center">@price.ToString("N0")</td>
                                    <td class="text-center">
                                        <button class="btn btn-primary Edit_InwardProduct" data-id="@item.Product.ID" title="Sửa số lượng sản phẩm"><i class="fa fa-pencil-square-o"></i></button>
                                        <button class="btn btn-danger Delete_InwardProduct" data-id="@item.Product.ID" title="Xóa sản phẩm"><i class="fa fa-times"></i></button>
                                    </td>
                                </tr>
                            }

                        }


                    </tbody>
                </table>
            </div>
        </div>
        @if (tong != 0)
        {
            <div class="row">
                <div class="col-md-8">
                    <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite"></div>
                </div>
                <div class="col-sm-4" style="margin-bottom:10px">
                    <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">
                        Tổng tiền: <span style="color:red; font-weight:bold; font-size:25px">@tong.ToString("N0")</span>vnđ
                    </div>
                </div>
            </div>
        }

        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-8">
                        @using (Html.BeginForm("AddInward", "Inward", FormMethod.Post, new { enctype = "multipart/form-data", id = "order_" }))
                        {
                            <input type="hidden" name="TotalAmount" value="@tong" />
                            <input type="hidden" name="TotalQuantity" value="@total_quantity" />
                            <input type="hidden" name="User_ID" value="@seller.ID" />
                            <div class="col-md-4"></div>
                            if (add_inward != null)
                            {
                                <div class="col-md-8">
                                    <button type="submit" class="btn btn-primary btn-lg">Nhập kho</button>
                                </div>
                            }

                        }

                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

@section jsSeller{

    <script>

        $(document).ready(function () {
            $(".select2").select2();
            

            $("#btnAdd_InwardProduct").click(function () {
                var product_id = $('#Product_ID').val();

                if (product_id == '') {
                    PNotify.error({
                        title: 'THÔNG BÁO!!',
                        text: 'Bạn vui lòng chọn sản phẩm.'
                    });
                    return;
                }

                var quantity = $('#Quantity').val();
                $.ajax({
                    url: '/Seller/Inward/addInwardProduct',
                    data: {
                        product_id: product_id,
                        quantity: quantity
                    },
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/Seller/Inward/Add";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm sản phẩm thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm sản phẩm KHÔNG thành công.'
                            });
                        }
                    }
                });
            });

            $(".Edit_InwardProduct").click(function () {
                var id = $(this).data('id');
                var Quantity = $('#txtQuantity-' + id).val();

                $.ajax({
                    data: {
                        ID: id,
                        Quantity: Quantity
                    },
                    url: '/Seller/Inward/Edit',
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/Seller/Inward/Add";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Sửa số lượng thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Thêm số lượng KHÔNG thành công.'
                            });
                        }
                    }
                });
            });

            $('.Delete_InwardProduct').off('click').on('click', function () {

                $.ajax({
                    data: { ID: $(this).data('id') },
                    url: '/Seller/Inward/Delete_InwardProduct',
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/Seller/Inward/Add";
                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Xóa sản phẩm thành công.'
                            });
                        } else {
                            PNotify.error({
                                title: 'THÔNG BÁO!!',
                                text: 'Xóa sản phẩm KHÔNG thành công.'
                            });
                        }
                    }
                });
            });

        });
    </script>

}

E - Shopper (web đồ điện tử)/Areas/Seller/Views/Inward/Index.cshtml
@using ShoppingOnline.Models.Entities;
@model PagedList.IPagedList<Inward>
@using PagedList.Mvc
@{
    ViewBag.Title = "Nhật ký nhập kho";
    Layout = "~/Areas/Seller/Views/Shared/_Layout.cshtml";
    var lstproduct_inward = ViewBag.quantity_product as List<Product>;
    int dem_1 = 0;
}

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <!-- /.col-lg-12 -->
            <div class="col-lg-12">
                <div class="col-md-4">
                    <h3 class="page-header">Nhật ký nhập kho</h3>
                </div>
                <div class="col-md-8" style="margin-top: 40px;">
                    <ol class="breadcrumb" style="text-align: right">
                        <li><a href="/Seller/Inward/Index"><i class="fa fa-inbox fa-fw"></i> Quản lý kho</a></li>
                        <li class="active">Nhật ký nhập kho</li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row">
            @if (TempData["add_success"] != null)
            {
                <div class="alert @TempData["alert"] text-center text-uppercase" id="AlertBox">
                    @TempData["add_success"]
                </div>
            }
        </div>
        <div class="row">
            <div class="col-md-4" style="margin-bottom: 10px">
                <a href="/Seller/Inward/Add" class="btn btn-lg btn-primary">Nhập kho </a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Nhật ký nhập kho
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr role="row">
                                        <th class="text-center">
                                            #
                                        </th>
                                        <th class="text-center">
                                            Thông tin đơn nhập
                                        </th>
                                        <th class="text-center">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        int dem = 0;

                                        foreach (var item in Model)
                                        {
                                            dem++;

                                            <tr class="gradeA even" role="row">
                                                <td class="text-center">@dem</td>
                                                <td>
                                                    <p>Tổng số lượng: <b>@item.TotalQuantity</b></p>
                                                    <p>Tổng tiền: <b>@item.TotalAmount.Value.ToString("N0")</b> đ</p>
                                                    <p>Ngày nhập: <b>@item.Createdate.Value.ToString("dd-MM-yyyy")</b></p>
                                                </td>
                                                <td class="text-center">
                                                    <a href="/Seller/Inward/Inward_Detail/@item.ID" class="btn btn-primary">
                                                        <i class="fa fa-calculator fa-fw" style="padding-right: 10px;"></i>Xem chi tiết
                                                    </a>
                                                </td>
                                            </tr>
                                        }

                                    }


                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <div class="panel-footer text-center">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = Model.PageSize }))
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
            <div class="col-sm-7">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Danh sách sản phẩm tồn kho
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th class="text-center">Mã sản phẩm</th>
                                        <th class="text-center">Tên sản phẩm</th>
                                        <th class="text-center">Số lượng tồn</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in lstproduct_inward)
                                    {
                                        dem_1++;
                                        <tr>
                                            <td>@dem_1</td>
                                            <td>@item.Product_Code</td>
                                            <td>@item.Product_Name</td>
                                            <td class="text-center">@item.Quantity</td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>

@section jsSeller{

    <script type="text/javascript">
        $(function () {

            //nếu không có thao tác gì thì ẩn đi
            $('#AlertBox').removeClass('hide');

            //Sau khi hiển thị lên thì delay 1s và cuộn lên trên sử dụng slideup
            $('#AlertBox').delay(2000).slideUp(500);


           
        });
    </script>

}